name: Main Channel Notifications

on:
  pull_request:
    branches:
      - development
      - main
    types: [closed]
jobs:
  notify-main:
    runs-on: ubuntu-latest

    steps:
      # If the actor is "merryymary", use DISCORD_WEBHOOK_MERRY
      - name: PR Merged to Main - Merry
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' && github.actor == 'merryymary'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_MERRY }}
          nodetail: true
          title: ""
          description: |
            ✅ ** Merry merged development to main**

            **PR Title:** ${{ github.event.pull_request.title }}
            **Branch:** ${{ github.event.pull_request.head.ref }} → ${{ github.event.pull_request.base.ref }}
            **PR ID:** ${{ github.event.pull_request.id }}

            **Summary**
            ${{ github.event.pull_request.body }}

            These changes will **go live** at the next server restart.
          color: 10824737

      - name: PR Merged to Development - Merry
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'development' && github.actor == 'merryymary'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_MERRY }}
          nodetail: true
          title: ""
          description: |
            ✅ ** Merry merged to development**
      
              **PR Title:** ${{ github.event.pull_request.title }}
              **Branch:** ${{ github.event.pull_request.head.ref }} → ${{ github.event.pull_request.base.ref }}
              **PR ID:** ${{ github.event.pull_request.id }}
              
              **Summary**
              ${{ github.event.pull_request.body }}
            
            This change will **not** be in the live server until it's merged
          color: 10824737 
